flask-base/app/blueprints/promos/forms.py
from flask_uploads import UploadSet, IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, SubmitField, SelectField, TextAreaField
from wtforms.validators import Length, Required

images = UploadSet('images', IMAGES)


class PhotoForm(FlaskForm):
    photo = FileField('Profile Picture', validators=[FileRequired(), FileAllowed(images, 'Images only!')])
    submit = SubmitField('Submit')


class ExtraForm(FlaskForm):
    photo = FileField('Upload submission documents only', validators=[FileRequired(), FileAllowed(images, 'Documents only!')])
    requirement_one = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_two = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_three = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_four = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_five = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_six = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_seven = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_eight = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_nine = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    requirement_ten = SelectField(u'Do you meet this requirement?', choices=[('Yes', 'Yes'), ('No', 'No')])
    submit = SubmitField('Submit')


class QuestionForm(FlaskForm):
    """ This is the question form  """
    title = StringField('Title', validators=[Required(), Length(min=50, max=150)])
    description = StringField('Description', validators=[Required(), Length(min=50, max=250)])
    submit = SubmitField('Submit')


class AnswerForm(FlaskForm):
    """ This is the question answers form  """
    body = TextAreaField('Answers', validators=[Required(), Length(min=50, max=5000)])
    submit = SubmitField('Submit')


class MessageForm(FlaskForm):
    """ This is the messageform  """
    body = TextAreaField('Message', validators=[Required(), Length(min=50, max=5000)])
    submit = SubmitField('Submit')


class ReplyForm(FlaskForm):
    """ This is the message reply form  """
    body = TextAreaField('Reply', validators=[Required(), Length(min=50, max=5000)])
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    """ This is the post(blog posts or articles) form  """
    body = TextAreaField('Post', validators=[Required(), Length(min=50, max=5000)])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    """ This is the comments form  """
    body = TextAreaField('Comments', validators=[Required(), Length(min=50, max=5000)])
    submit = SubmitField('Submit')


class InterestForm(FlaskForm):
    """ This is the interest declaration form  """
    interest_one = StringField('Professional networking')
    interest_two = StringField('Promo Opportunities')
    interest_three = StringField('Career Questions, Advice & Support')
    interest_four = StringField('Communications between colleagues and co-workers')
    submit = SubmitField('Submit')

flask-base/app/blueprints/promos/__init__.py
from app.blueprints.promos import errors  # noqa
from app.blueprints.promos.views import promos  # noqa

flask-base/app/blueprints/promos/views.py
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required

from app.models import *

promos = Blueprint('promos', __name__)


@promos.route('/list/')
def promos_list():
    #appts = Promo.query.filter(Promo.organisation != None).filter(Promo.end_date >= datetime.now()).order_by(Promo.pub_date.asc()).all()
    #return render_template('promos/allpromos.html', appts=appts)
    #def promos_list():
    appts = Promo.query.filter(Promo.organisation != None).filter(Promo.end_date >= datetime.now()).order_by(Promo.pub_date.asc()).all()
    return render_template('promos/allpromos.html', appts=appts)




@promos.route('/<int:promo_id>/<promo_title>/<promo_city>/<promo_state>/<promo_country>')
def promo_details(promo_id, promo_title, promo_city, promo_state, promo_country):
    appts = Promo.query.filter(Promo.id == promo_id).first_or_404()
    org_users = User.query.all()
    orgs = Organisation.query.filter(Organisation.user_id == User.id).all()
    return render_template('promos/promo_details.html', appt=appts, orgs=orgs, org_users=org_users)


@promos.route('/<int:promo_id>/<promo_title>/apply')
@login_required
def promo_apply(promo_id, promo_title):
    appt = db.session.query(Promo).get(promo_id)
    if appt is None:
        abort(404)
    elif current_user.id is None:
        abort(403)
    else:
        if appt.creator == current_user:
            flash("You can't participate in {0} because you created it".format(appt.promo_title), 'warning')
            return redirect(url_for('promos.promos_list'))
        extra = Extra.query.filter_by(user_id=current_user.id).first()
        #if not extra:
            #flash(
                #"You can't participate in {0} because you didn't complete your profile by adding the extra details required, please go to <a href='https://networked.ng{1}'>profile</a> to add it".format(
                    #appt.promo_title, url_for('account.change_extra_details')), 'warning')
            #return redirect(url_for('promos.promos_list'))
        submissions = Submission.query.filter(Submission.promo_id == appt.id).all()
        submissions = [appt.user_id for appt in submissions]
        if current_user.id in submissions:
            flash("You have <strong>already participated</strong> in {0}.".format(appt.promo_title), 'warning')
            return redirect(url_for('promos.promos_list'))
        else:
            appts = Submission(promo_id=appt.id, user_id=current_user.id)
            db.session.add(appts)
            db.session.commit()
            flash("You have successfully participated to {0}.".format(appt.promo_title), 'success')
            return redirect(url_for('promos.promos_list'))


@promos.route('/some-endpoint', methods=['POST'])
def share_email():
    share_text = "Your friend {0} on http://networked.ng want to recommend you this open course: {1}.\n" \
                 "Register, and view it here: {2}." \
                 "\n\n" \
                 "Regards,\n" \
                 "Networkednigeria team"

    formated_text = share_text.format(current_user.name, request.form['title'], request.form['url'])
    message = Message(subject="#Write Something Here!",
                      sender='#Write Something Here!',
                      reply_to=current_user.email,
                      recipients=[request.form['email']],
                      body=formated_text)
    mail.send(message)

    print(request.__dict__)
    print(request.form)
    return jsonify(status='success')

flask-base/app/templates/promos/allpromos.html
{% extends 'layouts/base.html' %}
{% import 'macros/promo_macros.html' as promo_wid %}

{% block content %}
    <div class="ui two column centered grid">
        <div class="column">
            <h1>Published promos</h1>
        </div>
    </div>
    <div class="ui grid">
        <div class="four wide column"></div>
        <div class="eight wide column">
            <div class="ui cards">
                {% for promo in appts %}
                    {{ promo_wid.promo_wid(promo) }}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

flask-base/app/templates/promos/common.html
{% macro detail(appt, link_title=true, show_edit=true, show_summary=true, show_modules=true) %}

    <div class="promo-detail">
    {% if show_edit %}
        <div class="edit-controls">
            <!----<a href="{{ url_for('promo_edit', promo_id=appt.id) }}"><i class="fa fa-pencil"></i></a>---->
            <!----<a class="extra-delete-link" href="{{ url_for('promo_delete', promo_id=appt.id) }}"><i class="fa fa-times"></i></a>----->
            <a href="{{ url_for('organisations.view_applicants', promo_id=appt.id) }}"><i class="fa fa-user"></i>
                <!--<span class="attendees_applied">3</span> --></a>
        </div>
    {% endif %}

    {% if link_title %}
        <div class="promo_title">
            <h3>
                <a href="{{ url_for('promo_details', promo_id=appt.id, promo_title=appt.promo_title, city=appt.city) }}">{{ appt.promo_title or '(No Title)' }}
                    in {{ appt.city }}</a>
            </h3>
        </div>
    {% else %}
        <h1 align="center">{{ appt.promo_title or '(No Title)' }} in {{ appt.city }}</h1>

        <hr>

        <h3 align="center"> Description</h3>
        <h6 align="center">{{ appt.description }}</h6>
        <hr>
    {% endif %}

    <!-- CREATED promoS VIEW -->
    <div class="date_published">
        <h4>Published:</h4>
        <span><i class="fa fa-calendar"></i> {{ appt.created_at.strftime('%d.%m.%Y ') }}</span>
    </div>
    <div class="url">

    </div>
    <div onclick="location.href='{{ url_for('promos.promo_details', promo_id=appt.id, promo_title=appt.promo_title, city=appt.city) }}';"
         style="cursor: pointer;">
        <div class="requirements">
            <h4><i class="fa fa-list"></i> Modules:</h4>
            {% if show_modules %}
                <ul>
                    {% if appt.requirement_one %}
                        <li>{{ appt.requirement_one|default('') }}</li>
                    {% else %}
                    {% endif %}

                    {% if appt.requirement_two %}
                        <li>{{ appt.requirement_two|default('') }}</li>
                    {% else %}
                    {% endif %}

                    {% if appt.requirement_three %}
                        <li>{{ appt.requirement_three|default('') }}</li>
                    {% else %}
                    {% endif %}

                    {% if appt.requirement_four %}
                        <li>{{ appt.requirement_four|default('') }}</li>
                    {% else %}
                    {% endif %}

                    {% if appt.requirement_five %}
                        <li>{{ appt.requirement_five|default('') }}</li>
                    {% else %}
                    {% endif %}

                    {% if appt.requirement_six %}
                        <li>{{ appt.requirement_six|default('') }}</li>
                    {% else %}
                    {% endif %}
                    {% if appt.requirement_seven %}
                        <li>{{ appt.requirement_seven|default('') }}</li>
                    {% else %}
                    {% endif %}
                    {% if appt.requirement_eight %}
                        <li>{{ appt.requirement_eight|default('') }}</li>
                    {% else %}
                    {% endif %}
                    {% if appt.requirement_nine %}
                        <li>{{ appt.requirement_nine|default('') }}</li>
                    {% else %}
                    {% endif %}
                    {% if appt.requirement_ten %}
                        <li>{{ appt.requirement_ten|default('') }}</li>
                    {% else %}
                    {% endif %}
                </ul>
            {% else %}
                <h4><i class="fa fa-external-link-square"></i> View complete details:</h4>
                <a href="{{ url_for('promo_details', promo_id=appt.id, promo_title=appt.promo_title, city=appt.city) }}"></a>
            {% endif %}
        </div>





        {% if show_summary and appt.summary_title %}
            <!---<div class="row">
              <p class="span5">-->
            {{ appt.summary_title | nl2br }}
            <!--</p>
          </div>-->
        {% endif %}

    </div>


{% endmacro %}

{% macro render_field(field) -%}
    {% set with_label = kwargs.pop('with_label', False) %}
    {% set placeholder = '' %}
    {% if not with_label %}
        {% set placeholder = field.label.text %}
    {% endif %}
    <div class="form-group {% if field.errors %}error{% endif %}">
        {% if with_label %}
            <label for="{{ field.id }}" class="control-label">
                {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
            </label>
        {% endif %}

        {% set class_ = kwargs.pop('class_', '') %}
        {% if field.flags.required %}
            {% set class_ = class_ + ' required' %}
        {% endif %}

        {% if field.type == 'BooleanField' %}
            <div class="checkbox">
                <label>
                    {{ field(class_=class_, **kwargs) }}
                    {{ field.label.text|safe }}
                </label>
            </div>

        {% else %}

            {% if field.type in ('TextField', 'TextAreaField', 'PasswordField') %}
                {% set class_ = class_ + ' input-xlarge form-control' %}

            {% elif field.type == 'FileField' %}
                {% set class_ = class_ + ' input-file form-control' %}
            {% endif %}

            {% if field.type == 'SelectField' %}
                {{ field(class_=class_, **kwargs) }}
            {% else %}

                {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
            {% endif %}

        {% endif %}
        {% if field.errors %}
            <span class="error help-inline">{{ field.errors|join(', ') }}</span>
        {% endif %}
        {% if field.description %}
            <p class="help-block">{{ field.description|safe }}</p>
        {% endif %}
    </div>
{%- endmacro %}

{% macro edit_field(field, catch_kwargs=true) %}
    <div class="form-group {% if field.errors %}error{% endif %}">
        <label for="{{ field.id }}" class="control-label">
            {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
        </label>

        {% set class_ = kwargs.pop('class_', '') %}
        {% if field.flags.required %}
            {% set class_ = class_ + ' required' %}
        {% endif %}

        {% if field.type == 'BooleanField' %}
            <div class="checkbox">
                <label>
                    {{ field(class_=class_, **kwargs) }}
                    {{ field.label.text|safe }}
                </label>
            </div>

        {% else %}

            {% if field.type in ('TextField', 'TextAreaField', 'PasswordField') %}
                {% set class_ = class_ + ' input-xlarge form-control' %}

            {% elif field.type == 'FileField' %}
                {% set class_ = class_ + ' input-file form-control' %}
            {% endif %}

            {% if field.type == 'SelectField' %}
                {{ field(class_=class_, **kwargs) }}
            {% else %}

                {{ field(class_=class_,  **kwargs) }}
            {% endif %}

        {% endif %}

        {% if field.errors %}
            <span class="error help-inline">{{ field.errors|join(', ') }}</span>
        {% endif %}
        {% if field.description %}
            <p class="help-block">{{ field.description|safe }}</p>
        {% endif %}

    </div>
{% endmacro %}

{% macro edit_field_old(field, catch_kwargs=true) %}
    <div class="control-group{% if field.errors %} error{% endif %}">
        {{ field.label(class="control-label") }}
        <div class="controls">
            {{ field(**kwargs) }}
            {% for error in field.errors %}<span class="help-inline">{{ error }}</span>{% endfor %}
        </div>
    </div>
{% endmacro %}

flask-base/app/templates/promos/commons.html
{% macro detail(appt, link_title=false, show_skills=true) %}

{% endmacro %}

{% macro edit_field(field, catch_kwargs=true) %}
    <div class="form-group {% if field.errors %}error{% endif %}">
        <label for="{{ field.id }}" class="control-label">
            {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
        </label>

        {% set class_ = kwargs.pop('class_', '') %}
        {% if field.flags.required %}
            {% set class_ = class_ + ' required' %}
        {% endif %}

        {% if field.type == 'BooleanField' %}
            <div class="checkbox">
                <label>
                    {{ field(class_=class_, **kwargs) }}
                    {{ field.label.text|safe }}
                </label>
            </div>

        {% else %}

            {% if field.type in ('TextField', 'TextAreaField', 'PasswordField') %}
                {% set class_ = class_ + ' input-xlarge form-control' %}

            {% elif field.type == 'FileField' %}
                {% set class_ = class_ + ' input-file form-control' %}
            {% endif %}

            {% if field.type == 'SelectField' %}
                {{ field(class_=class_, **kwargs) }}
            {% else %}

                {{ field(class_=class_,  **kwargs) }}
            {% endif %}

        {% endif %}

        {% if field.errors %}
            <span class="error help-inline">{{ field.errors|join(', ') }}</span>
        {% endif %}
        {% if field.description %}
            <p class="help-block">{{ field.description|safe }}</p>
        {% endif %}

    </div>
{% endmacro %}

{% macro edit_field_old(field, catch_kwargs=true) %}
    <div class="control-group{% if field.errors %} error{% endif %}">
        {{ field.label(class="control-label") }}
        <div class="controls">
            {{ field(**kwargs) }}
            {% for error in field.errors %}<span class="help-inline">{{ error }}</span>{% endfor %}
        </div>
    </div>
{% endmacro %}

flask-base/app/templates/promos/promo_details.html
{% extends 'layouts/base.html' %}
{% block page_title %}{{ appt.promo_title or '(No Title)' }} promo in {{ appt.promo_city|default('') }}{% endblock %}
{% block custom_head_tags %}
    <meta name="description"
          content="{{ appt.description }}">
    <meta name="author" content="{{ config.APP_NAME }}">
    <meta name="og:title" content="{{ appt.promo_title or '(No Title)' }}, {{ config.APP_NAME }} "/>
    <meta name="og:type" content="website"/>
    <meta name="og:url" content="https://www.{{ config.APP_NAME }}.com"/>
    <meta name="og:image" content="{{ url_for('static', filename='images/home/slider/hill.png') }}"/>
    <meta name="og:site_name" content="{{ config.APP_NAME }}"/>
    <meta name="og:description"
          content="{{ appt.description }}"/>
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:site" content="@medivillenetwork"/>
    <meta name="twitter:creator" content="@anioko1"/>
{% endblock %}
{% block content %}
    <div class="ui sixteen column centered grid">
        <div class="row edit-controls" align="center">
        </div>
        <div class="ui sixteen wide column created_promo">
            <h1>{{ appt.promo_title or '(No Title)' }}</h1>
            {{ share.load() }}
            <h3>
                {% if appt.creator != current_user %}
                    <a href="{{ url_for('promos.promo_apply', promo_id=appt.id, promo_title=appt.promo_title) }}">
                        <button style="margin-bottom: 20px;margin-right: 0;" type="button"
                                class="big ui teal button"></i> Participate in this promo
                        </button>
                    </a>
                {% else %}
                    <a href="{{ url_for('organisations.view_submissions', id=appt.id) }}">
                        <button style="margin-bottom: 20px;margin-right: 0;" type="button"
                                class="big ui teal button"></i>See Submissions
                        </button>
                    </a>
                {% endif %}
            </h3>
            <h3><i class="user outline icon"></i> Organisation: {{ appt.organisation.org_name }}</h3>
            <h3><i class="calendar outline icon"></i> Posted: {{ appt.pub_date.strftime( '%d %B, %Y ') }}</h3>
            <h3><i class="calendar outline icon"></i> End date: {{ appt.end_date.strftime( '%d %B, %Y ') }}</h3>
            <h3><i class="marker icon"></i> {{ appt.promo_city|default('') }},{{ appt.promo_country|default('') }}
            </h3>
            {% for org in org_users.user_organisations_created %}
                <h3><i class="building outkine icon"></i> Posted by: {{ org.org_name }}</h3>
            {% endfor %}

            {% for user in org_users %}
                {% for organisation in user.user_organisations_created %}
                    {{ organisation.org_name }}
                {% endfor %}
            {% endfor %}
            <div class="ui two column centered grid">
                <div class="column">
                    <hr>
                    <h4>Promo description</h4><!---I took out |default('')|markdown here---->
                    {{ appt.description }}
                    {{ share.create(title='Share with: ') }}
                    <hr>
                    <div class="requirements">
                        <h4><i class="fa fa-list"></i> Required Skills:</h4>
                        <ul>
                            {% if appt.requirement_one %}
                                <li>{{ appt.requirement_one|default('') }}</li>
                            {% else %}
                            {% endif %}

                            {% if appt.requirement_two %}
                                <li>{{ appt.requirement_two|default('') }}</li>
                            {% else %}
                            {% endif %}

                            {% if appt.requirement_three %}
                                <li>{{ appt.requirement_three|default('') }}</li>
                            {% else %}
                            {% endif %}

                            {% if appt.requirement_four %}
                                <li>{{ appt.requirement_four|default('') }}</li>
                            {% else %}
                            {% endif %}

                            {% if appt.requirement_five %}
                                <li>{{ appt.requirement_five|default('') }}</li>
                            {% else %}
                            {% endif %}

                            {% if appt.requirement_six %}
                                <li>{{ appt.requirement_six|default('') }}</li>
                            {% else %}
                            {% endif %}
                            {% if appt.requirement_seven %}
                                <li>{{ appt.requirement_seven|default('') }}</li>
                            {% else %}
                            {% endif %}
                            {% if appt.requirement_eight %}
                                <li>{{ appt.requirement_eight|default('') }}</li>
                            {% else %}
                            {% endif %}
                            {% if appt.requirement_nine %}
                                <li>{{ appt.requirement_nine|default('') }}</li>
                            {% else %}
                            {% endif %}
                            {% if appt.requirement_ten %}
                                <li>{{ appt.requirement_ten|default('') }}</li>
                            {% else %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row edit-controls" align="center">
                <h3>
                    {% if appt.creator != current_user %}
                        <a href="{{ url_for('promos.promo_apply', promo_id=appt.id, promo_title=appt.promo_title) }}">
                            <button style="margin-bottom: 20px;margin-right: 0;" type="button"
                                    class="big ui teal button"></i> Participate in this promo
                            </button>
                        </a>
                    {% else %}
                        <a href="{{ url_for('organisations.view_applicants', id=appt.id) }}">
                            <button style="margin-bottom: 20px;margin-right: 0;" type="button"
                                    class="big ui teal button"></i>See Submissions
                            </button>
                        </a>
                    {% endif %}
                </h3>
            </div>
        </div>
    </div>

    <div class="ui two column centered grid">
        <div class="column">
            <!--<div style="text-align:center;" class="row btn-group">-->

            <a href="http://www.facebook.com/sharer.php?u={{ url_for('promos.promo_details',promo_id=appt.id, promo_title=appt.promo_title,promo_city=appt.promo_city,promo_state=appt.promo_state, promo_country=appt.promo_country, _external=True) }}"
               title="On Facebook" target="_blank" class="btn btn-default" style="margin-right:-10px;">
                <i class="fa fa-facebook fa-2x"></i>
            </a>

            <a href="http://www.facebook.com/sharer.php?u={{ url_for('promos.promo_details',promo_id=appt.id, promo_title=appt.promo_title,promo_city=appt.promo_city,promo_state=appt.promo_state, promo_country=appt.promo_country, _external=True) }}"
               title="On Facebook" target="_blank" class="btn btn-default" style="margin-right:-10px;">
                <i class="fa fa-facebook fa-2x"></i>
            </a>

            <a href="https://twitter.com/intent/tweet?url={{ url_for('promos.promo_details',promo_id=appt.id, promo_title=appt.promo_title,promo_city=appt.promo_city,promo_state=appt.promo_state, promo_country=appt.promo_country, _external=True) }}&via=Teachera&text={{ appt.promo_title }}%20-%20Mediville.com!&hashtags={{ appt.promo_title }},{{ appt.promo_city }}"
               title="On Twitter" target="_blank" class="btn btn-default" style="margin-right:-10px;">
                <i class="fa fa-twitter fa-2x"></i>
            </a>


            <a href="http://www.linkedin.com/shareArticle?mini=true&url={{ url_for('promos.promo_details',promo_id=appt.id, promo_title=appt.promo_title,promo_city=appt.promo_city,promo_state=appt.promo_state, promo_country=appt.promo_country, _external=True) }}&title={{ appt.promo_title }} in {{ appt.promo_city }}&summary=Mediville.com!&source=http://Mediville.com"
               title="On LinkedIn" target="_blank" class="btn btn-default" style="margin-right:-10px;">
                <i class="fa fa-linkedin fa-2x"></i>
            </a>

            <a href="http://vk.com/share.php?url={{ url_for('promos.promo_details',promo_id=appt.id, promo_title=appt.promo_title,promo_city=appt.promo_city,promo_state=appt.promo_state, promo_country=appt.promo_country, _external=True) }}&title={{ appt.promo_title }} in {{ appt.promo_city }}&description=Mediville.com!&image=https%3A%2F%2Ffbcdn-sphotos-g-a.akamaihd.net%2Fhphotos-ak-frc3%2Ft1%2F10007500_219483098251971_1640217409_n.jpg"
               title="On VK.com" target="_blank" class="btn btn-default" style="margin-right:-10px;">
                <i class="fa fa-vk fa-2x"></i>
            </a>

            <a data-toggle="modal" href="#share-email-modal" class="btn btn-default" style="margin-right:-10px;">
                <i class="fa fa-share-alt fa-2x"></i>
            </a>
        </div>
    </div>

    </div>
    </div>


    <style>
        body {

            font-family: "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            line-height: 1.42857;
        }

        .applicants table {
            font-size: 1.2em;
            color: #1C3766;
        }

        .created_promo {
            font-family: 'Lato', sans-serif;
            color: #1C3766;
        }

        .created_promo h1 {
            font-size: 4em;
            font-weight: 600;
        }

        .created_promo h2 {
            font-size: 2.5em;
            font-weight: 400;
        }

        .created_promo h3 {
            font-size: 1.6em;
            margin: 10px 0 15px 0;
            font-weight: 500;
        }

        .created_promo h4 {
            font-size: 1.6em;
            font-weight: bold;
        }

        .created_promo p,
        .created_promo li {
            font-size: 1.3em;
        }

        .created_promo a {
            color: #5B6C7E;
            text-decoration: none;
            -webkit-transition: color .3s;
            -o-transition: color .3s;
            transition: color .3s;
            font-weight: 500;
            border-bottom: 2px solid;
        }

        .created_promo a:hover {
            color: #EC5805;
            text-decoration: none;
        }

        .created_promo h1,
        .created_promo h2,
        .created_promo h3 {
            text-align: center;
        }

        .created_promo .requirements ul li {
            promo: relative;
            text-transform: uppercase;
            font-weight: 500;
        }

        .organisation_details {
            padding: 60px 15px 10px 15px;
        }

        .share {
            padding-bottom: 40px;
        }

        @media (max-width: 768px) {
            .created_promo h1 {
                font-size: 2.7em;
            }

            .created_promo h2 {
                font-size: 2em;
            }

            .created_promo h3 {
                font-size: 1.4em;
            }
        }

    </style>
{% endblock %}
{% block scripts %}
    <script>
        jQuery(function ($) {
            $('form[data-async] #emailSaveBtn').click(function (event) {
                var $form = $(this);
                var $target = $($form.attr('data-target'));

                $.ajax({
                    type: 'POST',
                    url: '/some-endpoint',
                    data: {
                        email: $('#email').val(),
                        url: '{{ url_for('promos.promo_details',promo_id=appt.id, promo_title=appt.promo_title,promo_city=appt.promo_city,promo_state=appt.promo_state, promo_country=appt.promo_country,_external=True) }}',
                        title: '{{appt.course_title}} in {{appt.city}}',
                    },

                    success: function (data, status) {
                        console.log("success");
                        $('#share-email-modal').modal('hide');
                        $('#share-email-modal').modal('hide');
                    }

                });
                $('#share-email-modal').modal('hide');

                event.preventDefault();
            });
        });
        $('#share-email-modal').on('hidden.bs.modal', function (e) {
            $('#share-email-modal').modal('hide');
        })
    </script>
{% endblock %}