flask-base/app/models/profiles.py
from datetime import datetime

from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import query_expression

from app.utils import db, get_lang_name, whooshee
#from app import whooshee


@whooshee.register_model('first_name', 'last_name', 'title', 'header')
class Profile(db.Model):
    __tablename__ = 'profiles'

    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(64), index=True)
    last_name = db.Column(db.String(64), index=True)
    title = db.Column(db.String(256), index=True)
    header = db.Column(db.String(512), index=True)
    commitment = db.Column(db.String)
    type_of_work = db.Column(db.String)
    image = db.Column(db.String, default=None, nullable=True)
    cover = db.Column(db.String, default=None, nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='cascade'))

    user = db.relationship('User', backref='profiles')
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    score = query_expression()

    def employer_can_download(self, employer_id):
        return self.messages.filter(ProfileMessage.recipient_id == employer_id).first()

    @hybrid_property
    def full_name(self):
        return self.first_name + " " + self.last_name

    @property
    def completeness(self):
        perc = 10
        if self.skills:
            perc += 18
        if self.education:
            perc += 18
        if self.jobs:
            perc += 18
        if self.projects:
            perc += 18
        if self.languages:
            perc += 18

        return perc


# Please reflect any changes to this form in account/profile_edit.html template
@whooshee.register_model('name', 'description', 'exp')
class ProfileSkill(db.Model):
    __tablename__ = 'profile_skills'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(256), index=True)
    description = db.Column(db.String(512), index=True)
    exp = db.Column(db.String)#(name='commitment', N='Nobie', I='Intermediate', E='Experienced', G='Guru'))
    profile_id = db.Column(db.Integer, db.ForeignKey('profiles.id', ondelete='cascade'))

    profile = db.relationship('Profile', backref='skills')
    score = query_expression()


# Please reflect any changes to this form in account/profile_edit.html template
@whooshee.register_model('school', 'degree')
class ProfileEdu(db.Model):
    __tablename__ = 'profile_education'

    id = db.Column(db.Integer, primary_key=True)
    school = db.Column(db.String(256), index=True)
    degree = db.Column(db.String)#(name='commitment', A='Associate', B='Bachelor', M='Master', D='Doctoral'))
    start_date = db.Column(db.DateTime, nullable=False)
    end_date = db.Column(db.DateTime, default=None, nullable=True)
    profile_id = db.Column(db.Integer, db.ForeignKey('profiles.id', ondelete='cascade'))

    profile = db.relationship('Profile', backref='education')
    score = query_expression()


# Please reflect any changes to this form in account/profile_edit.html template
@whooshee.register_model('company', 'title')
class ProfileJob(db.Model):
    __tablename__ = 'profile_jobs'

    id = db.Column(db.Integer, primary_key=True)
    company = db.Column(db.String(256), index=True)
    title = db.Column(db.String(256), index=True)
    start_date = db.Column(db.DateTime, nullable=False)
    end_date = db.Column(db.DateTime, default=None, nullable=True)
    commitment = db.Column(db.String)#(name='commitment', F='Full Time', P='Part Time'))
    profile_id = db.Column(db.Integer, db.ForeignKey('profiles.id', ondelete='cascade'))

    profile = db.relationship('Profile', backref='jobs')
    score = query_expression()


# Please reflect any changes to this form in account/profile_edit.html template
@whooshee.register_model('lang', 'level')
class ProfileLang(db.Model):
    __tablename__ = 'profile_langs'

    id = db.Column(db.Integer, primary_key=True)
    lang = db.Column(db.String(2), index=True)
    level = db.Column(db.String)
    profile_id = db.Column(db.Integer, db.ForeignKey('profiles.id', ondelete='cascade'))

    profile = db.relationship('Profile', backref='languages')
    score = query_expression()

    @property
    def name(self):
        return get_lang_name(self.lang)

# Please reflect any changes to this form in account/profile_edit.html template
@whooshee.register_model('name', 'description', 'links')
class ProfileProject(db.Model):
    __tablename__ = 'profile_projects'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(256), index=True)
    description = db.Column(db.String(512), index=True)
    start_date = db.Column(db.DateTime, nullable=False)
    end_date = db.Column(db.DateTime, default=None, nullable=True)
    links = db.Column(db.JSON)
    profile_id = db.Column(db.Integer, db.ForeignKey('profiles.id', ondelete='cascade'))

    profile = db.relationship('Profile', backref='projects')
    score = query_expression()


class ProfileMessage(db.Model):
    __tablename__ = 'profile_messages'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='cascade'))
    recipient_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete="CASCADE"))
    profile_id = db.Column(db.Integer, db.ForeignKey('profiles.id', ondelete='cascade'))
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=db.func.now())
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())
    read_at = db.Column(db.DateTime, default=None, nullable=True)

    user = db.relationship('User', primaryjoin="ProfileMessage.user_id==User.id")
    # recipient = db.relationship('User', primaryjoin="ProfileMessage.recipient_id==User.id")
    profile = db.relationship('Profile', backref=db.backref('messages', lazy='dynamic'))

    def __repr__(self):
        return '<Message {}>'.format(self.body)

flask-base/app/blueprints/employer/__init__.py
from app.blueprints.employer.views import employer  # noqa
from app.blueprints.employer import errors  # noqa

flask-base/app/blueprints/employer/views.py
import operator
from datetime import datetime

from flask import Blueprint, render_template, request, flash, abort, make_response, redirect
from flask_login import login_required, current_user
from flask_sqlalchemy import Pagination
import pdfkit
from sqlalchemy import func

from app.blueprints.main.forms import MessageForm, Job#, ProfileMessage
from app.models import Profile, ProfileSkill, ProfileEdu, ProfileJob, ProfileLang, url_for, User
from app.utils import basedir, db

employer = Blueprint('employer', __name__)


@employer.route('/')
def index():
    return render_template('employer/index.html')


@employer.route('/search')
def search():
    query = request.args.get('query')
    page = request.args.get('page')
    sort_by = request.args.get('sort_by')
    sort_dir = request.args.get('sort_dir')
    search_type = request.args.get('type')

    query = query if query is not None else ''
    page = page if page is not None else 1
    search_type = search_type if search_type is not None else ''
    sort_by = sort_by if sort_by is not None else ''
    sort_dir = sort_dir if sort_dir is not None else ''
    try:
        page = int(page)
    except:
        page = 1
    if len(query) > 0 and len(query) < 3:
        flash("Search Query must be at least 3 characters", "error")
        return render_template('employer/search_results.html', query=query, search_type=search_type, sort_by=sort_by,
                           sort_dir=sort_dir, results=type('obj', (object,), {'total' : 0}))
    if len(query) > 0:
        profiles_results = Profile.query.whooshee_search(query, order_by_relevance=0).all()
        skills_results = ProfileSkill.query.whooshee_search(query, order_by_relevance=0).all()
        edu_results = ProfileEdu.query.whooshee_search(query, order_by_relevance=0).all()
        jobs_results = ProfileJob.query.whooshee_search(query, order_by_relevance=0).all()
        langs_results = ProfileLang.query.whooshee_search(query, order_by_relevance=0).all()
        projects_results = ProfileLang.query.whooshee_search(query, order_by_relevance=0).all()
        all_results = profiles_results + skills_results + edu_results + jobs_results + langs_results + projects_results
        results = sorted(all_results, key=operator.attrgetter("score"))


    else:
        results = Profile.query.order_by(Profile.created_at.desc()).all()

    # profiles_count = Profile.query.whooshee_search(query, order_by_relevance=0).count()
    # skills_count = ProfileSkill.query.whooshee_search(query, order_by_relevance=0).count()
    # edu_count = ProfileEdu.query.whooshee_search(query, order_by_relevance=0).count()
    # jobs_count = ProfileJob.query.whooshee_search(query, order_by_relevance=0).count()
    # langs_count = ProfileLang.query.whooshee_search(query, order_by_relevance=0).count()
    # projects_count = ProfileLang.query.whooshee_search(query, order_by_relevance=0).count()

    # all_count = profiles_count + skills_count + edu_count + jobs_count + langs_count + projects_count

    results.reverse()
    results = [result if result.__class__.__name__ == 'Profile' else result.profile for result in results]
    search_type = 'Full Time' if search_type == 'full' else 'Part Time' if search_type == 'part' else ''
    if search_type != '':
        results = [result for result in results if result.commitment == search_type]
    all_count = len(results)
    results = results[(page - 1) * 40:page * 40]
    paginator = Pagination(items=results, page=page, per_page=40, query=None, total=all_count)
    results = paginator
    return render_template('employer/search_results.html', query=query, search_type=search_type, sort_by=sort_by,
                           sort_dir=sort_dir, results=results)


@employer.route('/profile/<int:profile_id>')
def profile(profile_id):
    profile_instance = Profile.query.filter_by(id=profile_id).first()
    if not profile_instance:
        abort(404)
    return render_template("employer/profile_view.html", profile=profile_instance)


@employer.route('/profile/pdf/<int:profile_id>')
@login_required
def profile_pdf(profile_id):
    profile_instance = Profile.query.filter_by(id=profile_id).first()
    if not profile_instance:
        abort(404)
    if not profile_instance.employer_can_download(current_user.id):
        abort(401)
    rendered = render_template("employer/profile_pdf.html", profile=profile_instance)
    # return rendered
    config = pdfkit.configuration(wkhtmltopdf=bytes('/usr/bin/wkhtmltopdf', 'utf-8'))
    css = basedir+'/static/css/profile_pdf.css'
    pdf = pdfkit.from_string(rendered, False, configuration=config, css=css)
    response = make_response(pdf)
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = 'inline; filename=cv.pdf'
    return response


@employer.route('/profile/<int:profile_id>/contact')
@login_required
def hire(profile_id):
    profile_instance = Profile.query.filter_by(id=profile_id).first()
    if not profile_instance:
        abort(404)
    user = User.query.filter(User.id != current_user.id).filter_by(id=profile_instance.user.id).first_or_404()
    for message in current_user.professional_message_history(user.id, profile_id):
        if message.recipient_id == current_user.id:
            message.read_at = db.func.now()
        db.session.add(message)
    db.session.commit()
    form = MessageForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            msg = ProfileMessage(user_id=current_user.id, recipient=user,
                          body=form.message.data, profile_id=profile_id)
            db.session.add(msg)
            db.session.commit()
            user.add_notification('unread_message', {'message': msg.id, 'count': user.new_messages()},
                                  related_id=current_user.id, permanent=True)
            flash('Your message has been sent.')
            return redirect(url_for('main.send_message', recipient=user.id, full_name=user.full_name))
    follow_lists = User.query.filter(User.id != current_user.id).order_by(func.random()).limit(10).all()
    jobs = Job.query.filter(Job.organisation != None).filter(Job.end_date >= datetime.now()).order_by(
        Job.pub_date.asc()).all()
    return render_template("employer/profile_contact.html", profile=profile_instance, title='Send Message',
                           form=form, recipient=user, current_user=current_user, follow_lists=follow_lists, jobs=jobs)

flask-base/app/templates/employer/index.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <div class="ui grid container">
        <div class="ten wide computer sixteen wide mobile centered column">
            <h2 class="ui dividing header">Find Top Employees</h2>
            <div class="center">
                <div>
                    <form class="ui inline form fluid" style="width: 100%" method="GET" action="{{ url_for('employer.search') }}">
                        <div class="ui fluid icon input">
                            <input type="text" placeholder="Find Employees" name="query" autofocus>
                            <div class="ui button"> <i class="search icon"></i></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

flask-base/app/templates/employer/profile_view.html
{% extends 'layouts/base.html' %}
{% block page_title %}{{ profile.full_name }} - {{ profile.title }}{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="stretched divided very relaxed row">
            <div class="sixteen wide column">
                <div class="content">
                    <div id="app-root">
                        <div class="ui segment">
                            <div class="image" style="position: relative">
                                <div style="position: absolute;bottom: -80px;left: 1%;width: 100%; height: 180px;float: left;text-align: left;padding:05px;">
                                    <img style="height: 100%;width: 25%;min-width: 180px;border:4px solid rgb(98, 170, 175)"
                                         src="{{ url_for('_uploads.uploaded_file', setname='images',
                           filename=profile.image, _external=True) }}">
                                </div>
                                <img src="{{ url_for('_uploads.uploaded_file', setname='images',
                           filename=profile.cover, _external=True) }}" height="260" width="100%">
                            </div>
                            <div style="height: 90px"></div>
                            <div>
{#                                <a class="ui green icon button" target="_blank" href="{{ url_for('employer.profile_pdf', profile_id=profile.id) }}">Download Resume <i class="download icon"></i></a>#}
                                <a class="ui green right floated icon button" href="{{ url_for('employer.hire', profile_id=profile.id) }}">Hire Now <i class="handshake icon"></i></a>
                                <div class="content"><h3>{{ profile.full_name }}</h3></div>
                                <div class="content"><h4>{{ profile.title }} - {{ profile.type_of_work }} - {{
                                        profile.commitment }}</h4></div>
                                <div class="content"><h5>{{ profile.header }}</h5></div>
                            </div>
                            <br>
                        </div>
                        <!-- SKILLS -->
                        {% if profile.skills | length %}
                            <div class="ui segment">
                                <h2>Skills</h2>
                                <hr>
                                {% for skill in profile.skills %}
                                    <div style="background: #EEEEEE;margin-bottom: 1px;padding: 10px">
                                        <div>
                                            <h4>
                                                <i class="ui hand point right outline icon"></i>
                                                <strong><u>{{skill.exp}}</u></strong>
                                                <small>at</small>
                                                <strong><u>{{ skill.name }}</u></strong>
                                            </h4>
                                            <p style="text-indent: 20px;">{{skill.description}}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                                <hr>
                            </div>
                        {% endif %}
                        <!-- EDUCATION -->
                        {% if profile.education | length %}
                            <div class="ui segment">
                                <h2>Education</h2>
                                <hr>
                                {% for edu in profile.education %}
                                    <div style="background: #EEEEEE;margin-bottom: 1px;padding: 10px">
                                        <div>
                                            <div class="ui feed">
                                                <div class="event">
                                                    <div class="label">
                                                        <i class="ui calendar icon"></i>
                                                    </div>
                                                    <div class="content">
                                                        <div class="date">
                                                            {{edu.start_date | full_date}} <i
                                                                class="ui long arrow alternate right icon"></i>
                                                            {% if edu.end_date %}
                                                                <span>{{edu.end_date | full_date}}</span>
                                                            {% else %}
                                                                <span>Present</span>
                                                            {% endif %}
                                                        </div>
                                                        <div class="summary">
                                                            <a>{{edu.degree}} degree</a> -- <strong>{{edu.school}}</strong>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <hr>
                            </div>
                        {% endif %}
                        <!-- WORK -->
                        {% if profile.jobs | length %}
                            <div class="ui segment">
                                <h2>Work History</h2>
                                <hr>
                                {%  for job in profile.jobs %}
                                    <div style="background: #EEEEEE;margin-bottom: 1px;padding: 10px">
                                        <div>
                                            <div class="ui feed">
                                                <div class="event">
                                                    <div class="label">
                                                        <i class="ui calendar icon"></i>
                                                    </div>
                                                    <div class="content">
                                                        <div class="date">
                                                            {{job.start_date | full_date}} <i
                                                                class="ui long arrow alternate right icon"></i>
                                                            {% if job.end_date %}
                                                                <span>{{job.end_date | full_date}}</span>
                                                            {% else %}
                                                                <span>Present</span>
                                                            {% endif %}
                                                        </div>
                                                        <div class="summary">
                                                            <a>{{job.title}}</a> -- <strong>{{job.company}}</strong> --
                                                            {{job.commitment}}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <hr>
                            </div>
                        {% endif %}
                        <!-- PROJECTS -->
                        {% if profile.projects | length %}
                            <div class="ui segment">
                                <h2>Projects</h2>
                                <hr>
                                {% for project in profile.projects %}
                                    <div style="background: #EEEEEE;margin-bottom: 1px;padding: 10px">
                                        <div>
                                            <div class="ui feed">
                                                <div class="event">
                                                    <div class="label">
                                                        <i class="ui calendar icon"></i>
                                                    </div>
                                                    <div class="content">
                                                        <div class="date">
                                                            {{project.start_date | full_date}} <i
                                                                class="ui long arrow alternate right icon"></i>
                                                            {% if project.end_date %}
                                                                <span >{{project.end_date | full_date}}</span>
                                                            {% else %}
                                                                <span>Present</span>
                                                            {% endif %}
                                                        </div>
                                                        <div class="summary">
                                                            <a>{{project.name}}</a>
                                                            <p>{{project.description}}</p>
                                                            {% for link in json_load(project.links) %}
                                                                <a href="{{ link }}"
                                                                   target="_blank">{{link}}<br></a>
                                                            {% endfor %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <hr>
                            </div>
                        {% endif %}
                        <!-- LANGUAGES -->
                        {% if profile.languages | length %}
                            <div class="ui segment">
                                <h2>Languages</h2>
                                <hr>
                                {% for lang in profile.languages %}
                                    <div style="background: #EEEEEE;margin-bottom: 1px;padding: 10px">
                                        <div>
                                            <h4>
                                                <i class="ui hand point right outline icon"></i>
                                                <strong><u>{{lang.level}}</u></strong>
                                                <small>at</small>
                                                <strong><u>{{lang.name}}</u></strong>
                                            </h4>
                                        </div>
                                    </div>
                                {% endfor %}
                                <hr>
                            </div>
                        {% endif %}
                    </div>

                </div>

            </div>
        </div>
    </div>
    </div>

    {#    <a class="ui right floated icon button"><i class="plus  icon"></i> </a>#}

{% endblock %}
{% block scripts %}
    <script src="{{ url_for('static', filename='js/vue.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.0/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js" ></script>
    <script>

        function downloadCV() {
            let options = {
                background: '#fff',
                retina: true,
                pagesplit: true,
                margin: {
                    top: 50,
                    right: 25,
                    bottom: 50,
                    left: 25,
                    useFor: 'page' // This property is mandatory to keep the margin to supsequent pages
                }
            };
            let doc = new jsPDF('p','pt','a4');
            doc.internal.scaleFactor = 2.25;
            doc.addHTML($('#app-root'), 25, 50, options, function () {doc.save('sample-file.pdf');});

        }
    </script>

{% endblock %}