flask-base/app/blueprints/posts/forms.py
from flask_uploads import UploadSet, IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import RadioField, StringField, SubmitField, TextAreaField, MultipleFileField
from wtforms.validators import DataRequired, Length, Required

images = UploadSet('images', IMAGES)


class QuestionForm(FlaskForm):
    """ This is the question form  """
    title = StringField('Title', validators=[DataRequired(), Length(min=50, max=150)])
    description = TextAreaField('Description', validators=[DataRequired(), Length(min=50, max=850)])
    submit = SubmitField('Submit')


class SubmitForm(FlaskForm):
    name = StringField('Name your community or area or interest!', [Required()])
    desc = TextAreaField('Description of interest!', [Required()])
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    # image = FileField('Image', validators=[FileRequired(), FileAllowed(images, 'Images only!')])
    text = TextAreaField('')
    photo = MultipleFileField('Add Photos', validators=[FileAllowed(images, 'Images only!')])
    post_privacy = RadioField('Privacy', choices=[('0', 'Everyone'), ('1', 'Followers Only'), ('2', 'Private')],
                              default='0')
    submit = SubmitField('Submit')

flask-base/app/blueprints/posts/__init__.py
from app.blueprints.posts import errors  # noqa
from app.blueprints.posts.views import post_blueprint  # noqa

flask-base/app/blueprints/posts/views.py
import bleach
from flask import Blueprint, render_template, abort, flash, redirect, request, jsonify
from flask_login import current_user, login_required
from sqlalchemy import desc, func
from .forms import *
from app.models import * 


post_blueprint = Blueprint('post', __name__)




def clean(posts):
    for post in posts:
        post.text = bleach.clean(post.text)



@post_blueprint.route('/posts', methods=['GET', 'POST'])

@login_required
def post_create():
    form = PostForm()
    edit_form = PostForm()
    author = db.session.query(User).filter_by(id=current_user.id).first()
    if request.method == 'POST':
        if form.validate_on_submit():
            names_json, urls_json = "", ""
            if request.files['photo']:
                image_filenames = []
                image_urls = []
                for i, file in enumerate(request.files.getlist(form.photo.name)):
                    image_filename = images.save(file)
                    image_url = images.url(image_filename)
                    image_filenames.append({i: image_filename})
                    image_urls.append({i: image_url})
                names_json, urls_json = json.dumps(image_filenames), json.dumps(image_urls)
            
            posts = Post(
                image_filename=names_json,
                image_url=urls_json,
                text=form.text.data,
                post_privacy=form.post_privacy.data,
                user_id=current_user.id,
                author=author.full_name
            )
            author.newscaster_points = author.newscaster_points + 1
            author.newscaster_badge = get_level(author.newscaster_points) + " Newscaster"
            db.session.add(posts)
            db.session.commit()
            flash("Posted.", 'success')

            return redirect(url_for('post.post_create'))
        else:
            flash('ERROR! Post was not created.', 'error')
    else:
        form.photo.flags.required = False
        form.process()
    follow_lists = db.session.query(User).filter(User.id != current_user.id).order_by(func.random()).limit(10).all()
    jobs = db.session.query(Job).filter(Job.organisation != None).filter(Job.end_date >= datetime.now()).order_by(Job.pub_date.asc()).all()
    followed_ids = [f.id for f in current_user.followed.all()]
    posts = db.session.query(Post).order_by(Post.created_at.desc()).filter(or_(
        Post.user_id == current_user.id,
        and_(Post.user_id.in_(followed_ids), Post.post_privacy == 1),
        and_(Post.user_id != current_user.id, Post.post_privacy == 0))).limit(15).all()
    clean(posts)
    return render_template('posts/create_post.html', form=form,
                           follow_lists=follow_lists, jobs=jobs, 
                           author=author, edit_form=edit_form)

@post_blueprint.route('/load_more/<count>')
def load_more(count):
    count = int(count)
    followed_ids = [f.id for f in current_user.followed.all()]
    posts = db.session.query(Post).order_by(Post.created_at.desc()).filter(or_(
        Post.user_id == current_user.id,
        and_(Post.user_id.in_(followed_ids), Post.post_privacy == 1),
        and_(Post.user_id != current_user.id, Post.post_privacy == 0))).all()
    if count == 0:
        posts = posts[0:15]
    elif count >= len(posts):
        return "<br><br><h2>No more Posts</h2>"
    else:
        posts = posts[count:count + 15]
    clean(posts)
    return render_template('posts/posts.html', posts=posts)


@post_blueprint.route('/post/<post_id>', methods=['GET'])
#@cache.memoize(timeout=5)
@login_required
def view_post(post_id):
    #post = Post.query.filter_by(id=post_id).first_or_404()
    post = db.session.query(Post).filter_by(id=post_id).first_or_404()
    author = db.session.query(User).filter_by(full_name = post.author).first()
    follow_lists = db.session.query(User).filter(User.id != current_user.id).order_by(func.random()).limit(10).all()
    edit_form = PostForm()
    return render_template('posts/view_post.html', post=post, follow_lists=follow_lists, 
                            edit_form=edit_form, author=author)


@post_blueprint.route('/post/<post_id>/edit', methods=["POST"])
def edit_post(post_id):
    form = PostForm()
    if form.validate_on_submit():
        post = db.session.query(Post).filter_by(user_id=current_user.id).filter_by(id=post_id).first_or_404()
        names_json, urls_json = "", ""
        if request.files['photo']:
            image_filenames = []
            image_urls = []
            for i, file in enumerate(request.files.getlist(form.photo.name)):
                image_filename = images.save(file)
                image_url = images.url(image_filename)
                image_filenames.append({i: image_filename})
                image_urls.append({i: image_url})
            names_json, urls_json = json.dumps(image_filenames), json.dumps(image_urls)
        author = db.session.query(User).filter_by(id=current_user.id).first()
        if names_json and urls_json:
            post.image_filename = names_json,
            post.image_url = urls_json,
        post.text = form.text.data,
        post.post_privacy = form.post_privacy.data,
        post.author = author.full_name
        db.session.add(post)
        db.session.commit()
        flash("Post Updated Successfully.", 'success')

        return redirect(url_for('post.post_create'))
    else:
        flash('ERROR! Post was not edited.', 'error')


@post_blueprint.route('/post/<post_id>/delete', methods=['POST'])
def delete_post(post_id):
    post = db.session.query(Post).filter_by(user_id=current_user.id).filter_by(id=post_id).first_or_404()
    db.session.delete(post)
    db.session.commit()
    flash("Post Deleted Successfully.", 'success')
    return redirect(url_for('post.post_create'))


@post_blueprint.route('/like_post/<post_id>/<user_id>', methods=['POST'])
@login_required
def like_post(post_id, user_id):
    post_like = db.session.query(PostLike).filter_by(post_id=post_id).filter_by(user_id=user_id).first()
    if post_like:
        db.session.query(PostLike).filter_by(post_id=post_id).filter_by(user_id=user_id).delete()
    else:
        post_like = PostLike(
            post_id=post_id,
            user_id=user_id
        )
    db.session.add(post_like)
    db.session.commit()
    post_like = db.session.query(PostLike).filter_by(post_id=post_id).filter_by(user_id=user_id).first()
    if post_like:
        liked = 1
    else:
        liked = 0
    count = len(PostLike.query.filter_by(post_id=post_id).all())
    post = db.session.query(Post).get(post_id)
    post.creator.add_notification('post_likes', count, post_id)
    return json.dumps({
        'status': 'success',
        "count": count,
        "liked": liked
    })


@post_blueprint.route('/comment/<comment_id>/edit', methods=["POST"])
def edit_comment(comment_id):
    comment_text = request.form['comment_text']
    if not comment_text:
        abort(404)

    comment = db.session.query(Comment).get_or_404(int(comment_id))
    print(comment.post)
    if comment.author != current_user:
        abort(400)
    comment.text = comment_text
    db.session.add(comment)
    db.session.commit()
    flash("Comment Updated Successfully.", 'success')
    return redirect(url_for('post.post_create'))


@post_blueprint.route('/comment/<comment_id>/delete', methods=['POST'])
def delete_comment(comment_id):
    comment = db.session.query(Comment).get_or_404(int(comment_id))
    if comment.author != current_user:
        abort(400)
    db.session.delete(comment)
    db.session.commit()
    flash("Comment Deleted Successfully.", 'success')
    return redirect(url_for('post.post_create'))


##@post_blueprint.route('/interests')
##@login_required
##def view_interests():
##    interest = Interest.query.all()
##    return render_template('posts/all_interests.html', interest=interest)
##
##
##def meets_post_criteria(post):
##    if not post.title:
##        flash('You must include a title!', 'danger')
##        return False
##    if not post.text and not post.link:
##        flash('You must post either body text or a link!', 'danger')
##        return False
##
##    dup_link = post.query.filter_by(link=post.link).first()
##    if not post.text and dup_link:
##        flash('someone has already posted the same link as you!', 'danger')
##        return False
##
##    return True
##
##
##@post_blueprint.route('/<interest_name>/submit/', methods=['GET', 'POST'])
##def submit(interest_name=None):
##    """
##    """
##    if current_user is None:
##        flash('You must be logged in to submit posts!', 'danger')
##        return redirect(url_for('account.login', next=request.path))
##    user_id = current_user.user.id
##
##    interest = Interest.query.filter_by(name=interest_name).first()
##    if not interest:
##        abort(404)
##
##    form = SubmitForm(request.form)
##    if form.validate_on_submit():
##        title = form.title.data.strip()
##        link = form.link.data.strip()
##        text = form.text.data.strip()
##        post = Post(title=title, link=link, text=text,
##                    user_id=user_id, interest_id=interest.id)
##
##        if not meets_post_criteria(post):
##            return render_template('posts/submit.html', form=form, user=current_user.user,
##                                   cur_interest=interest.name)
##
##        db.session.add(post)
##        db.session.commit()
##        post.set_hotness()
##
##        flash('thanks for submitting!', 'success')
##        return redirect(url_for('post.view_interests', interest_name=interest.name))
##    return render_template('posts/submit.html', form=form, user=current_user.user,
##                           cur_interest=interest, interests=user.get_interests())


@post_blueprint.route('/comments/submit/', methods=['POST'])
@login_required
def submit_comment():
    post_id = int(request.form['post_id'])
    comment_text = request.form['comment_text']

flask-base/app/templates/posts/all_interests.html
{% extends 'layouts/base.html' %}


{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <h2 class="ui header">
                List of Interests Added

            </h2>
            <div class="ui items">
                {% for item in interest %}
                    <div class="item">
                        <i class="map marker icon"></i>
                        <div class="content">
                            <a class="header"><a
                                    href="{{ url_for('post.post_permalink', interest_name=interest.name, post_id=interest.id) }}">{{ item.name }}</a>
                                <div class="description">{{ item.desc }}</div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

flask-base/app/templates/posts/create_post.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/post_macros.html' as post_wid %}
{% import 'macros/job_macros.html' as job_wid %}
{% import 'macros/follow_macros.html' as follow_wid %}

{% block custom_head_tags %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lightbox/css/lightbox.min.css') }}">
    <style>
        .display-none {
            display: none;
        }
        .slick-prev:before, .slick-next:before {
            color: black;
        }
        .comment i.icon.ellipsis.vertical:before {
            font-size: 15px;
        }
        .comment .popup li a {
            color: rgba(0,0,0,.4);
        }
    </style>
{% endblock %}
{% block sidebars %}

{% endblock %}

{% block content %}
    <div class="ui grid container" id="example3">
        <div class="eight wide computer sixteen wide mobile centered column" id="scroller">

            {% set flashes = {
            'error':   get_flashed_messages(category_filter=['form-error']),
            'warning': get_flashed_messages(category_filter=['form-check-email']),
            'info':    get_flashed_messages(category_filter=['form-info']),
            'success': get_flashed_messages(category_filter=['form-success'])
		} %}

            {{ f.begin_form(form, flashes) }}
            <div class="ui grid">
                <div class="computer only row">
                    <div class="left ui rail">
                        <p></p>
                        <div class="ui sticky">
                            <h3 class="ui header">Colleagues to follow</h3>
                            <div class="ui divided items">
                                {% for user in follow_lists %}
                                    {{ follow_wid.follow_wid(user, current_user) }}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="right ui right rail">
                        <div class="ui sticky">
                            <div class="ui cards">
                                {% for job in jobs %}
                                    {{ job_wid.job_wid(job) }}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui grid">
                <div class="mobile only tablet only row">
                    <br>
                </div>
            </div>
            <div class="ui segment" style="background: ghostwhite;">
                <div class="ui form">
                    <form>
                        <div class="field">
                            {{ f.render_form_field(form.text) }}
                        </div>
                        <div class="field">
                            {{ f.render_form_field(form.photo) }}
                        </div>
                        <div class="field">
                            {{ f.render_form_field(form.post_privacy) }}
                        </div>
                        {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                        {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                        {{ f.form_message(flashes['info'], header='Information', class='info') }}
                        {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                        {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                            {{ f.render_form_field(field) }}
                        {% endfor %}

                    </form>
                </div>
            </div>
            {% for post in posts %}
                {{ post_wid.post_wid(post, moment, current_user) }}
            {% endfor %}
        </div>
        <div class="ui grid">
            <div class="mobile only tablet only row">
                <button class="circular ui huge blue icon floating action button">
                    <i class="large white icon tasks"></i>
                </button>

                <div class="ui right sidebar inverted menu">
                    <div class="ui padded grid">
                        <div class="ui cards">
                            {% for job in jobs %}
                                {{ job_wid.job_wid(job) }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="pusher">
                    <!-- Site content !-->
                </div>

            </div>
        </div>
        <div class="sixteen wide computer sixteen wide mobile centered column">
            <div class="ui">
                <p></p>
                <div class="ui active inverted dimmer" id="sentinel">
                    <div class="ui loader"></div>
                </div>
            </div>
        </div>
    </div>

    {% include 'partials/_post_modals.html' %}

{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='lightbox/js/lightbox.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.slick').slick({
                infinite: false,
            });
        });

        function like(post_id, user_id) {
            $.post("{{url_for('post.like_post', post_id=100, user_id=1000)}}".replace(/100/, post_id).replace(/1000/, user_id),
                {
                    csrf_token: "{{csrf_token()}}",
                },
                function (data, status) {
                    data = JSON.parse(data)
                    if (data.status == 'success') {
                        $("#like-count-" + post_id).html("(" + data.count + " likes) ");
                        if (data.liked == 1) {
                            $("#like-icon-" + post_id).removeClass("outline")
                        } else {
                            $("#like-icon-" + post_id).addClass("outline");
                        }
                    }
                });
        }
    </script>
    <script>
        $(document).ready(function () {
            $('.ui.sticky')
                .sticky({
                    offset: 50,
                    bottomOffset: 50,
                    context: '#example3'
                });
        })
    </script>
    <script>
        var counter = parseInt($('.post-card').length);
        function loadItems() {
            $.get("{{url_for('post.load_more', count=0)}}".replace(/0/, counter), function (data, status) {
                if (data == "<br><br><h2>No more Posts</h2>") {
                    $('#scroller').append($(data));
                    $('#sentinel').hide();
                    return;
                }
                $('#scroller').append($(data));
                $(document).ready(function () {
                    $('.slick:not(.slick-initialized)').slick({
                        infinite: false,
                    });
                    refreshImages();
                });
                counter = parseInt($('.post-card').length)
            });
        }

        var intersectionObserver = new IntersectionObserver(entries => {
            if (entries[0].intersectionRatio <= 0) {
                return;
            }
            loadItems();

        });
        intersectionObserver.observe(sentinel);
    </script>
{% endblock %}

flask-base/app/templates/posts/posts.html
{% import 'macros/form_macros.html' as f %}
{% import 'macros/comment_macros.html' as traverse %}
{% import 'macros/post_macros.html' as post_wid %}

{% for post in posts %}
    {{ post_wid.post_wid(post, moment, current_user) }}
{% endfor %}

flask-base/app/templates/posts/submit.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
    <div class="ui grid container">
        <div class="ui blue button">
            Add Interests
        </div>
        <div class="ui modal">
            <i class="close icon"></i>
            <div class="content">
                <h2 class="ui dividing header">Add your area of interest</h2>
                {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

                {{ f.begin_form(form, flashes) }}

                <div class="field">
                    {{ f.render_form_field(form.name) }}
                </div>
                <div class="field">
                    {{ f.render_form_field(form.desc) }}
                </div>


                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                {% endfor %}

                {{ f.end_form() }}

            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('.ui.blue.button').click(function () {

                $('.ui.modal').modal('show');
            });

        });

    </script>
{% endblock %}

flask-base/app/templates/posts/view_post.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/post_macros.html' as post_wid %}
{% import 'macros/job_macros.html' as job_wid %}
{% import 'macros/follow_macros.html' as follow_wid %}

{% block custom_head_tags %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lightbox/css/lightbox.min.css') }}">
    <style>
        .display-none {
            display: none;
        }
        .slick-prev:before, .slick-next:before {
            color: black;
        }
        .comment i.icon.ellipsis.vertical:before {
            font-size: 15px;
        }
        .comment .popup li a {
            color: rgba(0,0,0,.4);
        }
    </style>
{% endblock %}

{% block content %}
    <div class="ui grid container" id="example3">
        <div class="eight wide computer sixteen wide mobile centered column" id="scroller">

            {% set flashes = {
            'error':   get_flashed_messages(category_filter=['form-error']),
            'warning': get_flashed_messages(category_filter=['form-check-email']),
            'info':    get_flashed_messages(category_filter=['form-info']),
            'success': get_flashed_messages(category_filter=['form-success'])
		} %}

                <div class="left ui rail">
                    <p></p>
                    <div class="ui sticky">
                        <h3 class="ui header">Colleagues to follow</h3>
                        <div class="ui divided items">
                            {% for user in follow_lists %}
                                {{ follow_wid.follow_wid(user, current_user) }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="right ui right rail">
                    <div class="ui sticky">
                        <div class="ui cards">
                            {% for job in jobs %}
                                {{ job_wid.job_wid(job) }}
                            {% endfor %}
                        </div>
                    </div>
                </div>


                {{ post_wid.post_wid(post, moment, current_user) }}
        </div>
    </div>

    {% include 'partials/_post_modals.html' %}

{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='lightbox/js/lightbox.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.slick').slick({
                infinite: false,
            });
        });

        function like(post_id, user_id) {
            $.post("{{url_for('post.like_post', post_id=100, user_id=1000)}}".replace(/100/, post_id).replace(/1000/, user_id),
                {
                    csrf_token: "{{csrf_token()}}",
                },
                function (data, status) {
                    data = JSON.parse(data)
                    if (data.status == 'success') {
                        $("#like-count-" + post_id).html("(" + data.count + " likes) ");
                        if (data.liked == 1) {
                            $("#like-icon-" + post_id).removeClass("outline")
                        } else {
                            $("#like-icon-" + post_id).addClass("outline");
                        }
                    }
                });
        }
    </script>
    <script>
        $(document).ready(function () {
            $('.ui.sticky')
                .sticky({
                    offset: 50,
                    bottomOffset: 50,
                    context: '#example3'
                });
        })
    </script>
{% endblock %}